#define mini_language 1
#define do_start 2
#define do_end 3
#define do_do 4
#define intt 5
#define intts 6
#define stringg 7
#define stringgs 8
#define iff 9
#define elsee 10
#define writee 11
#define readd 12
#define each 13
#define whilee 14
#define new_line 15
#define add 16
#define sub 17
#define mul 18
#define div 19
#define not_eq 20
#define less 21
#define less_eq 22
#define eq 23
#define great 24
#define great_eq 25
#define ass 26
#define left_sq 27
#define right_sq 28